/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbmuniversity;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Asangi
 */
public class EnrolledCourse2 extends javax.swing.JFrame {
    DBOperation dbops = new DBOperation();
    String url = "jdbc:mysql://localhost:3306/nsbmuniversity";
    String username = "root";
    String password = "";
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet res = null;
    /**
     * Creates new form EnrolledCourse2
     */
    public EnrolledCourse2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtNameIni = new javax.swing.JTextField();
        ddDepName = new javax.swing.JComboBox<>();
        ddSubOneSemTwo = new javax.swing.JComboBox<>();
        ddSubTwoSemTwo = new javax.swing.JComboBox<>();
        ddSubThreeSemTwo = new javax.swing.JComboBox<>();
        ddSubFourSemTwo = new javax.swing.JComboBox<>();
        ddYearOfReg = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        ddCourse7Fee = new javax.swing.JComboBox<>();
        ddCourse6Fee = new javax.swing.JComboBox<>();
        ddCourse8Fee = new javax.swing.JComboBox<>();
        ddCourse5Fee = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        txtRegId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtfive = new javax.swing.JTextField();
        txtsix = new javax.swing.JTextField();
        txtseven = new javax.swing.JTextField();
        txteight = new javax.swing.JTextField();
        txtfeefive = new javax.swing.JTextField();
        txtfeesix = new javax.swing.JTextField();
        txtfeeseven = new javax.swing.JTextField();
        txtfeeeight = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txttotal1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Enrolled Course for July Register Student");
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Student Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(38, 55, 138, 24);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Department Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 90, 176, 23);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Subject 1 for Sem 2");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(31, 192, 145, 26);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Subject 2 for Sem 2");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(31, 224, 145, 26);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Subject 3 for Sem 2");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(31, 260, 145, 26);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Subject 4 for Sem 2");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(40, 304, 136, 26);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Year of Registration");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(32, 119, 144, 23);
        getContentPane().add(txtNameIni);
        txtNameIni.setBounds(194, 59, 168, 20);

        ddDepName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School of Business", "School of Computing", "School of Engineering" }));
        ddDepName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddDepNameActionPerformed(evt);
            }
        });
        getContentPane().add(ddDepName);
        ddDepName.setBounds(194, 93, 168, 20);

        ddSubOneSemTwo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Programming", "Discrete Mathematics", "Laboratary" }));
        ddSubOneSemTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddSubOneSemTwoActionPerformed(evt);
            }
        });
        getContentPane().add(ddSubOneSemTwo);
        ddSubOneSemTwo.setBounds(194, 192, 193, 20);

        ddSubTwoSemTwo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Data Structure and Algo", "Statics", "Mathematical Method" }));
        ddSubTwoSemTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddSubTwoSemTwoActionPerformed(evt);
            }
        });
        getContentPane().add(ddSubTwoSemTwo);
        ddSubTwoSemTwo.setBounds(194, 224, 193, 20);

        ddSubThreeSemTwo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Database", "Computer Network", "Automata" }));
        ddSubThreeSemTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddSubThreeSemTwoActionPerformed(evt);
            }
        });
        getContentPane().add(ddSubThreeSemTwo);
        ddSubThreeSemTwo.setBounds(194, 265, 193, 20);

        ddSubFourSemTwo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software Engineering", "Foundation of Computer Seince", "Computer System" }));
        ddSubFourSemTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddSubFourSemTwoActionPerformed(evt);
            }
        });
        getContentPane().add(ddSubFourSemTwo);
        ddSubFourSemTwo.setBounds(194, 309, 193, 20);

        ddYearOfReg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019" }));
        ddYearOfReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddYearOfRegActionPerformed(evt);
            }
        });
        getContentPane().add(ddYearOfReg);
        ddYearOfReg.setBounds(194, 122, 100, 20);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(194, 348, 57, 23);

        ddCourse7Fee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2500", "3000", "3500", "4000" }));
        getContentPane().add(ddCourse7Fee);
        ddCourse7Fee.setBounds(598, 265, 88, 20);

        ddCourse6Fee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2500", "3000", "3500", "4000" }));
        getContentPane().add(ddCourse6Fee);
        ddCourse6Fee.setBounds(596, 224, 90, 20);

        ddCourse8Fee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2500", "3000", "3500", "4000" }));
        getContentPane().add(ddCourse8Fee);
        ddCourse8Fee.setBounds(598, 309, 88, 20);

        ddCourse5Fee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2500", "3000", "3500", "4000" }));
        getContentPane().add(ddCourse5Fee);
        ddCourse5Fee.setBounds(596, 192, 88, 20);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Reg Id");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(31, 24, 145, 25);

        txtRegId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtRegId);
        txtRegId.setBounds(194, 28, 110, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select Subject Completing 10 Credit");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(67, 153, 554, 21);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(45, 348, 131, 23);
        getContentPane().add(txtfive);
        txtfive.setBounds(419, 192, 42, 20);
        getContentPane().add(txtsix);
        txtsix.setBounds(419, 224, 42, 20);
        getContentPane().add(txtseven);
        txtseven.setBounds(419, 265, 42, 20);
        getContentPane().add(txteight);
        txteight.setBounds(419, 309, 42, 20);
        getContentPane().add(txtfeefive);
        txtfeefive.setBounds(467, 192, 123, 20);

        txtfeesix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfeesixActionPerformed(evt);
            }
        });
        getContentPane().add(txtfeesix);
        txtfeesix.setBounds(467, 224, 123, 20);
        getContentPane().add(txtfeeseven);
        txtfeeseven.setBounds(467, 265, 125, 20);
        getContentPane().add(txtfeeeight);
        txtfeeeight.setBounds(467, 309, 125, 20);

        jButton2.setText("Total");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(393, 348, 68, 23);

        txttotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotal1ActionPerformed(evt);
            }
        });
        getContentPane().add(txttotal1);
        txttotal1.setBounds(419, 389, 42, 38);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 860, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ddSubOneSemTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddSubOneSemTwoActionPerformed
        try {
                con = (Connection) DriverManager.getConnection(url, username, password);
                pst = con.prepareStatement("SELECT coursedetails.credit , coursedetails.cozFee FROM coursedetails WHERE coursedetails.subName = '" + ddSubOneSemTwo.getSelectedItem().toString() + "' ");

                res = pst.executeQuery();
                while (res.next()) {
                    int credit = res.getInt(1);
                    String fee = res.getString(2);
                    txtfive.setText(Integer.toString(credit));
                    txtfeefive.setText(fee);
            }
            }catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_ddSubOneSemTwoActionPerformed

    private void ddYearOfRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddYearOfRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddYearOfRegActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(Integer.parseInt(txttotal1.getText())==10){
        
        EnrolledCourseDetails2 ecd2 = new EnrolledCourseDetails2();
        ecd2.setRegId(Integer.parseInt(txtRegId.getText()));
        ecd2.setName(txtNameIni.getText());
        ecd2.setDepName(ddDepName.getSelectedItem().toString());
        ecd2.setYearOfReg(ddYearOfReg.getSelectedItem().toString());
        ecd2.setSemTwoSubOne(ddSubOneSemTwo.getSelectedItem().toString());
        ecd2.setCourseFiveFee(Integer.parseInt(ddCourse5Fee.getSelectedItem().toString()));
        ecd2.setSemTwoSubTwo(ddSubTwoSemTwo.getSelectedItem().toString());
        ecd2.setCourseSixFee(Integer.parseInt(ddCourse6Fee.getSelectedItem().toString()));
        ecd2.setSemTwoSubThree(ddSubThreeSemTwo.getSelectedItem().toString());
        ecd2.setCourseSevenFee(Integer.parseInt(ddCourse7Fee.getSelectedItem().toString()));
        ecd2.setSemTwoSubFour(ddSubFourSemTwo.getSelectedItem().toString());
        ecd2.setCourseEghitFee(Integer.parseInt(ddCourse8Fee.getSelectedItem().toString()));
        if(dbops.EnrolledCourse2(ecd2)){
            JOptionPane.showMessageDialog(this, "Succsefully !!");
            clearField();
        }
        else{
            JOptionPane.showMessageDialog(this, "Unsuccessfully!!");
            clearField();
        }
        }else {
            JOptionPane.showMessageDialog(this, "Please complete amount of credit  correctly");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void ddDepNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddDepNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddDepNameActionPerformed

    private void ddSubFourSemTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddSubFourSemTwoActionPerformed
        try {
                con = (Connection) DriverManager.getConnection(url, username, password);
                pst = con.prepareStatement("SELECT coursedetails.credit ,coursedetails.cozFee  FROM coursedetails WHERE coursedetails.subName = '" + ddSubFourSemTwo.getSelectedItem().toString() + "' ");

                res = pst.executeQuery();
                while (res.next()) {
                    int credit = res.getInt(1);
                    String fee = res.getString(2);
                    txteight.setText(Integer.toString(credit));
                    txtfeeeight.setText(fee);
                
            }
            }catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_ddSubFourSemTwoActionPerformed

    private void txtRegIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        PostGraduateDetail pd = new PostGraduateDetail();
        pd.setVisible(true);
        pd.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtfeesixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfeesixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfeesixActionPerformed

    private void ddSubTwoSemTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddSubTwoSemTwoActionPerformed
        try {
                con = (Connection) DriverManager.getConnection(url, username, password);
                pst = con.prepareStatement("SELECT coursedetails.credit , coursedetails.cozFee FROM coursedetails WHERE coursedetails.subName = '" + ddSubTwoSemTwo.getSelectedItem().toString() + "' ");

                res = pst.executeQuery();
                while (res.next()) {
                    int credit = res.getInt(1);
                    String fee  = res.getString(2);
                    txtsix.setText(Integer.toString(credit));
                    txtfeesix.setText(fee);
                
            }
            }catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_ddSubTwoSemTwoActionPerformed

    private void ddSubThreeSemTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddSubThreeSemTwoActionPerformed
        try {
                con = (Connection) DriverManager.getConnection(url, username, password);
                pst = con.prepareStatement("SELECT coursedetails.credit , coursedetails.cozFee FROM coursedetails WHERE coursedetails.subName = '" + ddSubThreeSemTwo.getSelectedItem().toString() + "' ");

                res = pst.executeQuery();
                while (res.next()) {
                    int credit = res.getInt(1);
                    String fee = res.getString(2);
                    txtseven.setText(Integer.toString(credit));
                    txtfeeseven.setText(fee);
            }
            }catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_ddSubThreeSemTwoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int cre5 = Integer.parseInt(txtfive.getText());
        int cre6 = Integer.parseInt(txtsix.getText());
        int cre7 = Integer.parseInt(txtseven.getText());
        int cre8 = Integer.parseInt(txteight.getText());
        int total = cre5+cre6+cre7+cre8;
        txttotal1.setText(Integer.toString(total));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txttotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotal1ActionPerformed
    void clearField(){
          txtNameIni.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnrolledCourse2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnrolledCourse2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnrolledCourse2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnrolledCourse2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnrolledCourse2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> ddCourse5Fee;
    private javax.swing.JComboBox<String> ddCourse6Fee;
    private javax.swing.JComboBox<String> ddCourse7Fee;
    private javax.swing.JComboBox<String> ddCourse8Fee;
    private javax.swing.JComboBox<String> ddDepName;
    private javax.swing.JComboBox<String> ddSubFourSemTwo;
    private javax.swing.JComboBox<String> ddSubOneSemTwo;
    private javax.swing.JComboBox<String> ddSubThreeSemTwo;
    private javax.swing.JComboBox<String> ddSubTwoSemTwo;
    private javax.swing.JComboBox<String> ddYearOfReg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNameIni;
    private javax.swing.JTextField txtRegId;
    private javax.swing.JTextField txteight;
    private javax.swing.JTextField txtfeeeight;
    private javax.swing.JTextField txtfeefive;
    private javax.swing.JTextField txtfeeseven;
    private javax.swing.JTextField txtfeesix;
    private javax.swing.JTextField txtfive;
    private javax.swing.JTextField txtseven;
    private javax.swing.JTextField txtsix;
    private javax.swing.JTextField txttotal1;
    // End of variables declaration//GEN-END:variables
}
