/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbmuniversity;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author Asangi
 */
public class ResultSheet extends javax.swing.JFrame {
    DBOperation dbops = new DBOperation();
    String url = "jdbc:mysql://localhost:3306/nsbmuniversity";
    String username = "root";
    String password = "";
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet res = null;
    PreparedStatement pst1 = null;
    ResultSet res1 = null;
    PreparedStatement pst2 = null;
    ResultSet res2 = null;
    PreparedStatement pst3 = null;
    ResultSet res3 = null;
    PreparedStatement pst4 = null;
    ResultSet res4 = null;
    /**
     * Creates new form ResultSheet
     */
    public ResultSheet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblSubThree = new javax.swing.JLabel();
        lblSubTwo = new javax.swing.JLabel();
        lblSubOne = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSemOneSubOne = new javax.swing.JTextField();
        txtSemOneSubTwo = new javax.swing.JTextField();
        txtSemOneSubThree = new javax.swing.JTextField();
        txtSemOneSubFour = new javax.swing.JTextField();
        txtSemTwoSubOne = new javax.swing.JTextField();
        txtSemTwoSubTwo = new javax.swing.JTextField();
        txtSemTwoSubThree = new javax.swing.JTextField();
        txtSemTwoSubFour = new javax.swing.JTextField();
        ddSemOneSubOne = new javax.swing.JComboBox<>();
        ddSemOneSubTwo = new javax.swing.JComboBox<>();
        ddSemOneSubThree = new javax.swing.JComboBox<>();
        ddSemOneSubFour = new javax.swing.JComboBox<>();
        ddSemTwoSubOne = new javax.swing.JComboBox<>();
        ddSemTwoSubTwo = new javax.swing.JComboBox<>();
        ddSemTwoSubThree = new javax.swing.JComboBox<>();
        ddSemTwoSubFour = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        ddSubOne = new javax.swing.JComboBox<>();
        ddSubTwo = new javax.swing.JComboBox<>();
        ddSubThree = new javax.swing.JComboBox<>();
        txtRegId = new javax.swing.JTextField();
        txtNameIni = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnEnter = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMasage = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtToGmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("RegId");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Student Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Subject 1 for Sem 1");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Subject 2 for Sem 1");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Subject 3 for Sem 1");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Subject 4 for Sem 1");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Subject 1 for Sem 2");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Subject 2 for Sem 2");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Subject 3 for Sem 2");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Subject 4 for Sem 2");

        lblSubThree.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSubThree.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSubThree.setText("Progarmming Concept");

        lblSubTwo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSubTwo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSubTwo.setText("Operating System");

        lblSubOne.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSubOne.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSubOne.setText("Automata");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Compulsary Subject");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Optional Subject");

        txtSemOneSubThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSemOneSubThreeActionPerformed(evt);
            }
        });

        ddSemOneSubOne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", "AB" }));

        ddSemOneSubTwo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", "AB" }));

        ddSemOneSubThree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", "AB" }));

        ddSemOneSubFour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", "AB" }));

        ddSemTwoSubOne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", "AB" }));

        ddSemTwoSubTwo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", "AB" }));

        ddSemTwoSubThree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", "AB" }));

        ddSemTwoSubFour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", "AB" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Exame result");

        ddSubOne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", "AB" }));

        ddSubTwo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", "AB" }));

        ddSubThree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-", "F", "AB" }));

        txtRegId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegIdActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Subject 1 ");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Subject 2 ");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Subject 3 ");

        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Massage");

        txtMasage.setColumns(20);
        txtMasage.setRows(5);
        jScrollPane1.setViewportView(txtMasage);

        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Email Address");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSemOneSubOne, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                            .addComponent(txtSemOneSubTwo)
                                            .addComponent(txtSemOneSubThree)
                                            .addComponent(txtSemOneSubFour)
                                            .addComponent(txtSemTwoSubOne)
                                            .addComponent(txtSemTwoSubTwo)
                                            .addComponent(txtSemTwoSubThree)
                                            .addComponent(txtSemTwoSubFour))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtRegId, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(txtNameIni, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(28, 28, 28)
                                            .addComponent(jButton1))))
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSubTwo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSubThree, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(lblSubOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ddSemOneSubOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ddSemOneSubTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ddSemOneSubThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ddSemOneSubFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ddSemTwoSubOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ddSemTwoSubTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ddSemTwoSubThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ddSemTwoSubFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ddSubOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ddSubTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ddSubThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtToGmail, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnter))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSubOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ddSubOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSubTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ddSubTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ddSubThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSubThree, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSemOneSubOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddSemOneSubOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSemOneSubTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddSemOneSubTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSemOneSubThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddSemOneSubThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSemOneSubFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddSemOneSubFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSemTwoSubOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddSemTwoSubOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSemTwoSubTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddSemTwoSubTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSemTwoSubThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddSemTwoSubThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSemTwoSubFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ddSemTwoSubFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtToGmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSemOneSubThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSemOneSubThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSemOneSubThreeActionPerformed

    private void txtRegIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegIdActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
          try {
            con = (Connection) DriverManager.getConnection(url, username, password);
            pst = con.prepareStatement("SELECT registerdetailspart1.name FROM registerdetailspart1 WHERE registerdetailspart1.regId = '" + txtRegId.getText() + "' ");

            res = pst.executeQuery();

            while (res.next()) {
                String name = res.getString(1);
                
                txtNameIni.setText(name);
                
            }

            pst1 = con.prepareStatement("SELECT undergraduateenrolledcourse.regId FROM undergraduateenrolledcourse WHERE undergraduateenrolledcourse.regId = '" + txtRegId.getText() + "'");
            res1 = pst1.executeQuery();
            
            int regId1 = 0;
            int regId2 = 0;
            int regId3 = 0;
            int regId4 = 0;
            
            while (res1.next()) {
                regId1 = res1.getInt(1);
            }
            pst2 = con.prepareStatement("SELECT undergraduateenrolledcourse2.regId FROM undergraduateenrolledcourse2 WHERE undergraduateenrolledcourse2.regId = '" + txtRegId.getText() + "'");
            res2 = pst2.executeQuery();
            while (res2.next()) {
                regId2 = res2.getInt(1);
            }
            
            pst3 = con.prepareStatement("SELECT enrolledcourse.regId FROM enrolledcourse WHERE enrolledcourse.regId = '" + txtRegId.getText() + "'");
            res3 = pst3.executeQuery();
            while (res3.next()) {
                regId3 = res3.getInt(1);
            }
            
            pst4 = con.prepareStatement("SELECT enrolledcourse2.regId FROM enrolledcourse2 WHERE enrolledcourse2.regId = '" + txtRegId.getText() + "'");
            res4 = pst4.executeQuery();
            while (res4.next()) {
                regId4 = res4.getInt(1);
            }
            
            if (Integer.parseInt(txtRegId.getText()) == regId1) {
                pst1 = con.prepareStatement("SELECT undergraduateenrolledcourse.semOneSubOne , undergraduateenrolledcourse.semOneSubTwo ,undergraduateenrolledcourse.semOneSubThree , undergraduateenrolledcourse.semOneSubFour , undergraduateenrolledcourse.semTwoSubOne ,undergraduateenrolledcourse.semTwoSubTwo,undergraduateenrolledcourse.semTwoSubThree ,undergraduateenrolledcourse.semTwoSubFour FROM undergraduateenrolledcourse WHERE undergraduateenrolledcourse.regId = '" + txtRegId.getText() + "' ");
                res1 = pst1.executeQuery();

                while (res1.next()) {
                    
                    String semOneSubOne = res1.getString(1);
                    String semOneSubTwo = res1.getString(2);
                    String semOneSubThree = res1.getString(3);
                    String semOneSubFour = res1.getString(4);
                    String semTwoSubOne = res1.getString(5);
                    String semTwoSubTwo = res1.getString(6);
                    String semTwoSubThree = res1.getString(7);
                    String semTwoSubFour = res1.getString(8);
                    
                    txtSemOneSubOne.setText(semOneSubOne);
                    txtSemOneSubTwo.setText(semOneSubTwo);
                    txtSemOneSubThree.setText(semOneSubThree);
                    txtSemOneSubFour.setText(semOneSubFour);
                    txtSemTwoSubOne.setText(semTwoSubOne);
                    txtSemTwoSubTwo.setText(semTwoSubTwo);
                    txtSemTwoSubThree.setText(semTwoSubThree);
                    txtSemTwoSubFour.setText(semTwoSubFour);
                }
            }else if (Integer.parseInt(txtRegId.getText()) == regId2) {
                pst2 = con.prepareStatement("SELECT undergraduateenrolledcourse2.semTwoSubOne ,undergraduateenrolledcourse2.semTwoSubTwo,undergraduateenrolledcourse2.semTwoSubThree ,undergraduateenrolledcourse2.semTwoSubFour FROM undergraduateenrolledcourse2 WHERE undergraduateenrolledcourse2.regId = '" + txtRegId.getText() + "' ");
                res2 = pst2.executeQuery();

                while (res2.next()) {
                    

                    String semTwoSubOne = res2.getString(1);
                    String semTwoSubTwo = res2.getString(2);
                    String semTwoSubThree = res2.getString(3);
                    String semTwoSubFour = res2.getString(4);
                    

                    txtSemTwoSubOne.setText(semTwoSubOne);
                    txtSemTwoSubTwo.setText(semTwoSubTwo);
                    txtSemTwoSubThree.setText(semTwoSubThree);
                    txtSemTwoSubFour.setText(semTwoSubFour);
                }
            }else if (Integer.parseInt(txtRegId.getText()) == regId3) {
                pst3 = con.prepareStatement("SELECT  enrolledcourse.semOneSubOne , enrolledcourse.semOneSubTwo ,enrolledcourse.semOneSubThree , enrolledcourse.semOneSubFour , enrolledcourse.semTwoSubOne ,enrolledcourse.semTwoSubTwo,enrolledcourse.semTwoSubThree ,enrolledcourse.semTwoSubFour FROM enrolledcourse WHERE enrolledcourse.regId = '" + txtRegId.getText() + "' ");
                res3 = pst3.executeQuery();

                while (res3.next()) {
                    
                    String semOneSubOne = res3.getString(1);
                    String semOneSubTwo = res3.getString(2);
                    String semOneSubThree = res3.getString(3);
                    String semOneSubFour = res3.getString(4);
                    String semTwoSubOne = res3.getString(5);
                    String semTwoSubTwo = res3.getString(6);
                    String semTwoSubThree = res3.getString(7);
                    String semTwoSubFour = res3.getString(8);
                    
                    txtSemOneSubOne.setText(semOneSubOne);
                    txtSemOneSubTwo.setText(semOneSubTwo);
                    txtSemOneSubThree.setText(semOneSubThree);
                    txtSemOneSubFour.setText(semOneSubFour);
                    txtSemTwoSubOne.setText(semTwoSubOne);
                    txtSemTwoSubTwo.setText(semTwoSubTwo);
                    txtSemTwoSubThree.setText(semTwoSubThree);
                    txtSemTwoSubFour.setText(semTwoSubFour);
                }
            }else if (Integer.parseInt(txtRegId.getText()) == regId4) {
                pst4 = con.prepareStatement("SELECT enrolledcourse2.semTwoSubOne ,enrolledcourse2.semTwoSubTwo,enrolledcourse2.semTwoSubThree ,enrolledcourse2.semTwoSubFour FROM enrolledcourse2 WHERE enrolledcourse2.regId = '" + txtRegId.getText() + "' ");
                res4 = pst4.executeQuery();

                while (res4.next()) {
                    
                    String semTwoSubOne = res4.getString(1);
                    String semTwoSubTwo = res4.getString(2);
                    String semTwoSubThree = res4.getString(3);
                    String semTwoSubFour = res4.getString(4);
                    

                    txtSemTwoSubOne.setText(semTwoSubOne);
                    txtSemTwoSubTwo.setText(semTwoSubTwo);
                    txtSemTwoSubThree.setText(semTwoSubThree);
                    txtSemTwoSubFour.setText(semTwoSubFour);
                }
            }

        } catch (Exception e) {
            System.out.println("x");
            System.out.println(e);
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        try{
        
        
            con = (Connection) DriverManager.getConnection(url, username, password);
        
            pst1 = con.prepareStatement("SELECT undergraduateenrolledcourse.regId FROM undergraduateenrolledcourse WHERE undergraduateenrolledcourse.regId = '" + txtRegId.getText() + "'");
            res1 = pst1.executeQuery();
            
            int regId1 = 0;
            int regId2 = 0;
            int regId3 = 0;
            int regId4 = 0;
            
            while (res1.next()) {
                regId1 = res1.getInt(1);
            }
            pst2 = con.prepareStatement("SELECT undergraduateenrolledcourse2.regId FROM undergraduateenrolledcourse2 WHERE undergraduateenrolledcourse2.regId = '" + txtRegId.getText() + "'");
            res2 = pst2.executeQuery();
            while (res2.next()) {
                regId2 = res2.getInt(1);
            }
            
            pst3 = con.prepareStatement("SELECT enrolledcourse.regId FROM enrolledcourse WHERE enrolledcourse.regId = '" + txtRegId.getText() + "'");
            res3 = pst3.executeQuery();
            while (res3.next()) {
                regId3 = res3.getInt(1);
            }
            
            pst4 = con.prepareStatement("SELECT enrolledcourse2.regId FROM enrolledcourse2 WHERE enrolledcourse2.regId = '" + txtRegId.getText() + "'");
            res4 = pst4.executeQuery();
            while (res4.next()) {
                regId4 = res4.getInt(1);
            }
            if (Integer.parseInt(txtRegId.getText()) == regId1) {
                this.dispose();
                Result rs= new Result();
                rs.setRegId(Integer.parseInt(txtRegId.getText()));
                rs.setName(txtNameIni.getText());
                rs.setSubone(lblSubOne.getText());
                rs.setResultone(ddSubOne.getSelectedItem().toString());
                rs.setSubtwo(lblSubTwo.getText());
                rs.setResulttwo(ddSubTwo.getSelectedItem().toString());
                rs.setSubthree(lblSubThree.getText());
                rs.setResultthree(ddSubThree.getSelectedItem().toString());
                rs.setSemOneSubOne(txtSemOneSubOne.getText());
                rs.setResultfour(ddSemOneSubOne.getSelectedItem().toString());
                rs.setSemOneSubTwo(txtSemOneSubTwo.getText());
                rs.setResultfive(ddSemOneSubTwo.getSelectedItem().toString());
                rs.setSemOneSubThree(txtSemOneSubThree.getText());
                rs.setResultsix(ddSemOneSubThree.getSelectedItem().toString());
                rs.setSemOneSubFour(txtSemOneSubFour.getText());
                rs.setResultseven(ddSemOneSubFour.getSelectedItem().toString());
                rs.setSemTwoSubOne(txtSemTwoSubOne.getText());
                rs.setResultegiht(ddSemTwoSubOne.getSelectedItem().toString());
                rs.setSemTwoSubTwo(txtSemTwoSubTwo.getText());
                rs.setResultnine(ddSemTwoSubTwo.getSelectedItem().toString());
                rs.setSemTwoSubThree(txtSemTwoSubThree.getText());
                rs.setResultten(ddSemTwoSubThree.getSelectedItem().toString());
                rs.setSemTwoSubFour(txtSemTwoSubFour.getText());
                rs.setResulteleven(ddSemTwoSubFour.getSelectedItem().toString());
                if(dbops.examresultenter(rs)){
                    JOptionPane.showMessageDialog(this, "Succsefully !!");
                    clearField();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Unsuccessfully!!");
                    clearField();
                }
            }
            if (Integer.parseInt(txtRegId.getText()) == regId2) {
                this.dispose();
                Result rs= new Result();
                rs.setRegId(Integer.parseInt(txtRegId.getText()));
                rs.setName(txtNameIni.getText());
                rs.setSubone(lblSubOne.getText());
                rs.setResultone(ddSubOne.getSelectedItem().toString());
                rs.setSubtwo(lblSubTwo.getText());
                rs.setResulttwo(ddSubTwo.getSelectedItem().toString());
                rs.setSubthree(lblSubThree.getText());
                rs.setResultthree(ddSubThree.getSelectedItem().toString());
                rs.setSemOneSubOne("");
                rs.setResultfour("");
                rs.setSemOneSubTwo("");
                rs.setResultfive("");
                rs.setSemOneSubThree("");
                rs.setResultsix("");
                rs.setSemOneSubFour("");
                rs.setResultseven("");
                rs.setSemTwoSubOne(txtSemTwoSubOne.getText());
                rs.setResultegiht(ddSemTwoSubOne.getSelectedItem().toString());
                rs.setSemTwoSubTwo(txtSemTwoSubTwo.getText());
                rs.setResultnine(ddSemTwoSubTwo.getSelectedItem().toString());
                rs.setSemTwoSubThree(txtSemTwoSubThree.getText());
                rs.setResultten(ddSemTwoSubThree.getSelectedItem().toString());
                rs.setSemTwoSubFour(txtSemTwoSubFour.getText());
                rs.setResulteleven(ddSemTwoSubFour.getSelectedItem().toString());
                if(dbops.examresultenter(rs)){
                    JOptionPane.showMessageDialog(this, "Succsefully !!");
                    clearField();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Unsuccessfully!!");
                    clearField();
                }
            }
            if (Integer.parseInt(txtRegId.getText()) == regId3) {
                this.dispose();
                Result rs= new Result();
                rs.setRegId(Integer.parseInt(txtRegId.getText()));
                rs.setName(txtNameIni.getText());
                rs.setSubone(lblSubOne.getText());
                rs.setResultone(ddSubOne.getSelectedItem().toString());
                rs.setSubtwo(lblSubTwo.getText());
                rs.setResulttwo(ddSubTwo.getSelectedItem().toString());
                rs.setSubthree(lblSubThree.getText());
                rs.setResultthree(ddSubThree.getSelectedItem().toString());
                rs.setSemOneSubOne(txtSemOneSubOne.getText());
                rs.setResultfour(ddSemOneSubOne.getSelectedItem().toString());
                rs.setSemOneSubTwo(txtSemOneSubTwo.getText());
                rs.setResultfive(ddSemOneSubTwo.getSelectedItem().toString());
                rs.setSemOneSubThree(txtSemOneSubThree.getText());
                rs.setResultsix(ddSemOneSubThree.getSelectedItem().toString());
                rs.setSemOneSubFour(txtSemOneSubFour.getText());
                rs.setResultseven(ddSemOneSubFour.getSelectedItem().toString());
                rs.setSemTwoSubOne(txtSemTwoSubOne.getText());
                rs.setResultegiht(ddSemTwoSubOne.getSelectedItem().toString());
                rs.setSemTwoSubTwo(txtSemTwoSubTwo.getText());
                rs.setResultnine(ddSemTwoSubTwo.getSelectedItem().toString());
                rs.setSemTwoSubThree(txtSemTwoSubThree.getText());
                rs.setResultten(ddSemTwoSubThree.getSelectedItem().toString());
                rs.setSemTwoSubFour(txtSemTwoSubFour.getText());
                rs.setResulteleven(ddSemTwoSubFour.getSelectedItem().toString());
                if(dbops.examresultenter(rs)){
                    JOptionPane.showMessageDialog(this, "Succsefully !!");
                    clearField();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Unsuccessfully!!");
                    clearField();
                }
            }
            if (Integer.parseInt(txtRegId.getText()) == regId4) {
                this.dispose();
                Result rs= new Result();
                rs.setRegId(Integer.parseInt(txtRegId.getText()));
                rs.setName(txtNameIni.getText());
                rs.setSubone(lblSubOne.getText());
                rs.setResultone(ddSubOne.getSelectedItem().toString());
                rs.setSubtwo(lblSubTwo.getText());
                rs.setResulttwo(ddSubTwo.getSelectedItem().toString());
                rs.setSubthree(lblSubThree.getText());
                rs.setResultthree(ddSubThree.getSelectedItem().toString());
                rs.setSemOneSubOne("");
                rs.setResultfour("");
                rs.setSemOneSubTwo("");
                rs.setResultfive("");
                rs.setSemOneSubThree("");
                rs.setResultsix("");
                rs.setSemOneSubFour("");
                rs.setResultseven("");
                rs.setSemTwoSubOne(txtSemTwoSubOne.getText());
                rs.setResultegiht(ddSemTwoSubOne.getSelectedItem().toString());
                rs.setSemTwoSubTwo(txtSemTwoSubTwo.getText());
                rs.setResultnine(ddSemTwoSubTwo.getSelectedItem().toString());
                rs.setSemTwoSubThree(txtSemTwoSubThree.getText());
                rs.setResultten(ddSemTwoSubThree.getSelectedItem().toString());
                rs.setSemTwoSubFour(txtSemTwoSubFour.getText());
                rs.setResulteleven(ddSemTwoSubFour.getSelectedItem().toString());
                if(dbops.examresultenter(rs)){
                    JOptionPane.showMessageDialog(this, "Succsefully !!");
                    
                }
                else{
                    JOptionPane.showMessageDialog(this, "Unsuccessfully!!");
                    
                }
            }
        
        
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            con = (Connection) DriverManager.getConnection(url, username, password);
            
                    
           
            
           
                pst = con.prepareStatement("SELECT examresultsheet.name ,examresultsheet.subone ,examresultsheet.resultone, examresultsheet.subtwo ,examresultsheet.resulttwo ,examresultsheet.subthree , examresultsheet.resultthree , examresultsheet.semonesubone ,examresultsheet.resultfour ,examresultsheet.semonesubtwo ,examresultsheet.resultfive ,examresultsheet.semonesubthree ,examresultsheet.resultsix,examresultsheet.semonesubfour,examresultsheet.resultseven ,examresultsheet.semtwosubone ,examresultsheet.resulteight ,examresultsheet.semtwosubtwo ,examresultsheet.resultnine ,examresultsheet.semtwosubthree ,examresultsheet.resultten, examresultsheet.semtwosubfour ,examresultsheet.resulteleven  FROM examresultsheet WHERE examresultsheet.regId = '"+txtRegId.getText()+"' ");
            
                res = pst.executeQuery();
                while (res.next()) {
                    String name = res.getString(1);
                    String subOne = res.getString(2);
                    String result1 = res.getString(3);
                    String subTwo = res.getString(4);
                    String result2 = res.getString(5);
                    String subThree = res.getString(6);
                    String result3 = res.getString(7);
                    String semOneSubOne = res.getString(8);
                    String result4 = res.getString(9);
                    String semOneSubTwo = res.getString(10);
                    String result5 = res.getString(11);
                    String semOneSubThree = res.getString(12);
                    String result6 = res.getString(13);
                    String semOneSubFour = res.getString(14);
                    String result7 = res.getString(15);
                    String semTwoSubOne = res.getString(16);
                    String result8 = res.getString(17);
                    String semTwoSubTwo = res.getString(18);
                    String result9 = res.getString(19);
                    String semTwoSubThree = res.getString(20);
                    String result10 = res.getString(21);
                    String semTwoSubFour = res.getString(22);
                    String result11 = res.getString(23);
                    
                    txtMasage.setText("Hello"+name+" This is your Marks for the exam result\n\nSubject = "+subOne+" Result---> "+result1+"\n\nSubject = "+subTwo+" Result----> "+result2+"\n\nSubject = "+subThree+" Result----> "+result3+"\n\nSubject = "+semOneSubOne+" Result----> "+result4+"\n\nSubject = "+semOneSubTwo+" Result----> "+result5+"\n\nSubject = "+semOneSubThree+" Result----> "+result6+"\n\nSubject = "+semOneSubFour+" Result----> "+result7+"\n\nSubject = "+semTwoSubOne+" Result----> "+result8+"\n\nSubject = "+semTwoSubTwo+" Result----> "+result9+"\n\nSubject = "+semTwoSubThree+" Result----> "+result10+"\n\nSubject = "+semTwoSubFour+" Result----> "+result11);
                    
                    
                }
                pst = con.prepareStatement("SELECT registerdetailspart1.email FROM registerdetailspart1 WHERE registerdetailspart1.regId ="+txtRegId.getText());
            
               res= pst.executeQuery();
               while(res.next()){
                    String to = res.getString(1);
                
                    txtToGmail.setText(to);
                
                 
                
            }
                
            
            
        }catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            String host = "mail.javatpoint.com";
            String user ="ucsc1995asangi@gmail.com";
            String password = "abcbcs95@";
            String to = txtToGmail.getText();
            Properties pros = System.getProperties();
            pros.setProperty("mail.smtp.host",host);
            pros.put("mail.smtp.starttls.enable", true);
            pros.put("mail.smtp.host", "smtp.gmail.com");
            pros.put("mail.smtp.socketFactory.port", "465");
            pros.put("mail.smtp.auth", "true");
            pros.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");
            Session session = Session.getDefaultInstance(pros , 
            new javax.mail.Authenticator(){
                protected PasswordAuthentication getPasswordAuthentication(){
                    return new PasswordAuthentication(user,password);
                }
            });
            try{
                
                MimeMessage message = new MimeMessage(session);
                message.setFrom(new InternetAddress(user));
                message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
                message.setSubject("Exame result");
                message.setText(txtMasage.getText());
                
                Transport.send(message);
                System.out.println("message sent successfully...");
               
            JOptionPane.showMessageDialog(null, "Message send Succsefully!!!");
            
        
        }
            
        catch(MessagingException em){
            em.printStackTrace();
        }
           clearField();
    }//GEN-LAST:event_jButton2ActionPerformed
    void clearField(){
        txtRegId.setText("");
        txtNameIni.setText("");
        
        txtSemOneSubOne.setText("");
        txtSemOneSubTwo.setText("");
        txtSemOneSubThree.setText("");
        txtSemOneSubFour.setText("");
        txtSemTwoSubOne.setText("");
        txtSemTwoSubTwo.setText("");
        txtSemTwoSubThree.setText("");
        txtSemTwoSubFour.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultSheet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> ddSemOneSubFour;
    private javax.swing.JComboBox<String> ddSemOneSubOne;
    private javax.swing.JComboBox<String> ddSemOneSubThree;
    private javax.swing.JComboBox<String> ddSemOneSubTwo;
    private javax.swing.JComboBox<String> ddSemTwoSubFour;
    private javax.swing.JComboBox<String> ddSemTwoSubOne;
    private javax.swing.JComboBox<String> ddSemTwoSubThree;
    private javax.swing.JComboBox<String> ddSemTwoSubTwo;
    private javax.swing.JComboBox<String> ddSubOne;
    private javax.swing.JComboBox<String> ddSubThree;
    private javax.swing.JComboBox<String> ddSubTwo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSubOne;
    private javax.swing.JLabel lblSubThree;
    private javax.swing.JLabel lblSubTwo;
    private javax.swing.JTextArea txtMasage;
    private javax.swing.JTextField txtNameIni;
    private javax.swing.JTextField txtRegId;
    private javax.swing.JTextField txtSemOneSubFour;
    private javax.swing.JTextField txtSemOneSubOne;
    private javax.swing.JTextField txtSemOneSubThree;
    private javax.swing.JTextField txtSemOneSubTwo;
    private javax.swing.JTextField txtSemTwoSubFour;
    private javax.swing.JTextField txtSemTwoSubOne;
    private javax.swing.JTextField txtSemTwoSubThree;
    private javax.swing.JTextField txtSemTwoSubTwo;
    private javax.swing.JTextField txtToGmail;
    // End of variables declaration//GEN-END:variables
}
