/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbmuniversity;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Asangi
 */
public class Save extends javax.swing.JFrame {
  
    /**
     * Creates new form Save
     */
    String url = "jdbc:mysql://localhost:3306/nsbmuniversity";
    String username = "root";
    String password = "";
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet res = null;
    ArrayList<SaveInstrucorDetails> inlist;
    ArrayList<SaveLectureDetails> lelist;
    ArrayList<SaveDepartmentDetails> dplist;
    ArrayList<SaveCourseDetails> czlist;
    DBOperation dbops = new DBOperation();
    public Save() {
        initComponents();
        loadInDetail();
        loadLeckDetail();
        loadDpDetail();
        loadCzDetail();
    }
    void loadInDetail(){
       inlist =dbops.getInsructor();
       InstructerRecords instructRe = new  InstructerRecords (inlist);
       tblInstruct.setModel(instructRe);
       
    
    }
    void loadLeckDetail(){
       lelist =dbops.getLecture();
       LectureRecords lecRe = new  LectureRecords(lelist);
       txtLec.setModel(lecRe);
       
    
    }
    void loadDpDetail(){
       dplist =dbops.getDepartment();
       DepartmentRecords depRe = new  DepartmentRecords(dplist);
       tblDep.setModel(depRe);
       
    
    }
    void loadCzDetail(){
       czlist =dbops.getCourse();
       CourseRecords depRe = new  CourseRecords(czlist);
       tblCourse.setModel(depRe);
       
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btnAddLec = new javax.swing.JButton();
        btnViewLec = new javax.swing.JButton();
        btnDeleteLec = new javax.swing.JButton();
        btnUpdateLec = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtLec = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnAddIns = new javax.swing.JButton();
        btnViewIns = new javax.swing.JButton();
        btnDeleteIns = new javax.swing.JButton();
        btnUpdateIns = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblInstruct = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtSearchName2 = new javax.swing.JTextField();
        btnSearch3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAddCz = new javax.swing.JButton();
        btnViewCz = new javax.swing.JButton();
        btnDeleteCz = new javax.swing.JButton();
        btnUpdateCz = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();
        btnSearch2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSearchName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnAddDep = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDep = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Save Details");
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(255, 204, 204));

        btnAddLec.setText("Add Lecture");
        btnAddLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLecActionPerformed(evt);
            }
        });

        btnViewLec.setText("View Lecture");
        btnViewLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLecActionPerformed(evt);
            }
        });

        btnDeleteLec.setText("Delete Lecture");
        btnDeleteLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLecActionPerformed(evt);
            }
        });

        btnUpdateLec.setText("Update Lecture");
        btnUpdateLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateLecActionPerformed(evt);
            }
        });

        txtLec.setBackground(new java.awt.Color(204, 204, 255));
        txtLec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Lecture Id", "Lecture Name", "Email", "Contact Number", "Department Name"
            }
        ));
        jScrollPane4.setViewportView(txtLec);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddLec, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnViewLec, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnUpdateLec, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSearch))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDeleteLec, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddLec, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewLec, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateLec, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteLec, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lectures", jPanel3);

        btnAddIns.setText("Add Instructor");
        btnAddIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInsActionPerformed(evt);
            }
        });

        btnViewIns.setText("View Instructor");
        btnViewIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInsActionPerformed(evt);
            }
        });

        btnDeleteIns.setText("Delete Instructor");
        btnDeleteIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteInsActionPerformed(evt);
            }
        });

        btnUpdateIns.setText("Update Instructor");
        btnUpdateIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateInsActionPerformed(evt);
            }
        });

        tblInstruct.setBackground(new java.awt.Color(204, 204, 255));
        tblInstruct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Instructor Id", "Instructor Name", "Email", "Contact Number", "Department Name"
            }
        ));
        jScrollPane5.setViewportView(tblInstruct);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Name");

        txtSearchName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchName2ActionPerformed(evt);
            }
        });

        btnSearch3.setText("Search");
        btnSearch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddIns, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnViewIns, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdateIns, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSearchName2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDeleteIns, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(btnSearch3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddIns, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewIns, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateIns, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteIns, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchName2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Instructor", jPanel4);

        btnAddCz.setText("Add Course");
        btnAddCz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCzActionPerformed(evt);
            }
        });

        btnViewCz.setText("View Course");
        btnViewCz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCzActionPerformed(evt);
            }
        });

        btnDeleteCz.setText("Delete Course");
        btnDeleteCz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCzActionPerformed(evt);
            }
        });

        btnUpdateCz.setText("Update Course");
        btnUpdateCz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCzActionPerformed(evt);
            }
        });

        tblCourse.setBackground(new java.awt.Color(204, 204, 255));
        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Subject Id", "Subject Name", "credit", "Department Name", "Semester", "Lecture Name", "Lab Number", "Course Fee"
            }
        ));
        jScrollPane3.setViewportView(tblCourse);

        btnSearch2.setText("Search");
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name");

        txtSearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddCz, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnViewCz, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdateCz, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSearchName))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteCz, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCz, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateCz, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewCz, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCz, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Course ", jPanel2);

        btnAddDep.setText("Add Department");
        btnAddDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDepActionPerformed(evt);
            }
        });

        tblDep.setBackground(new java.awt.Color(204, 204, 255));
        tblDep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Department Code", "Department Name"
            }
        ));
        jScrollPane2.setViewportView(tblDep);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddDep, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnAddDep, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Department", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(-2, -2, 820, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLecActionPerformed
        SaveLecture sl = new SaveLecture();
        sl.setVisible(true);
        sl.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnAddLecActionPerformed

    private void btnUpdateCzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCzActionPerformed
        UpdateCourse uc = new UpdateCourse();
        uc.setVisible(true);
        uc.setFields(czlist.get(tblCourse.getSelectedRow()));
    }//GEN-LAST:event_btnUpdateCzActionPerformed

    private void btnViewCzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCzActionPerformed
        ViewCourse vc = new ViewCourse();
        vc.setVisible(true);
        vc.setFields(czlist.get(tblCourse.getSelectedRow()));
    }//GEN-LAST:event_btnViewCzActionPerformed

    private void btnAddCzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCzActionPerformed
        SaveCourse sc = new SaveCourse();
        sc.setVisible(true);
        sc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnAddCzActionPerformed

    private void btnAddDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDepActionPerformed
        SaveDepartment sd = new SaveDepartment();
        sd.setVisible(true);
        sd.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnAddDepActionPerformed

    private void btnAddInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInsActionPerformed
        SaveInstructor si = new SaveInstructor();
        si.setVisible(true);
        si.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnAddInsActionPerformed

    private void btnDeleteLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLecActionPerformed
        DeleteLecture dl = new DeleteLecture();
        dl.setVisible(true);
        dl.setFields(lelist.get(txtLec.getSelectedRow()));
    }//GEN-LAST:event_btnDeleteLecActionPerformed

    private void btnUpdateLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateLecActionPerformed
        LectureUpdate lu = new LectureUpdate();
        lu.setVisible(true);
        lu.setFields(lelist.get(txtLec.getSelectedRow()));
    }//GEN-LAST:event_btnUpdateLecActionPerformed

    private void btnViewLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLecActionPerformed
        ViewLecture vl = new ViewLecture();
        vl.setVisible(true);
        vl.setFields(lelist.get(txtLec.getSelectedRow()));
    }//GEN-LAST:event_btnViewLecActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       try{
            con = (Connection) DriverManager.getConnection(url, username, password);
            String name = txtSearch.getText();
            String sql = "Select lecId , lecName , email , telNo , depName from lecturedetails where lecName LIKE '%"+name+"%' ";
            pst = (PreparedStatement) con.prepareStatement(sql); 
            res = pst.executeQuery();
            
            txtLec.setModel(DbUtils.resultSetToTableModel(res));
       }catch(Exception e){
               
               }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchNameActionPerformed

    private void txtSearchName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchName2ActionPerformed

    private void btnDeleteCzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCzActionPerformed
        
        DeleteCourse dc = new DeleteCourse();
        dc.setVisible(true);
        dc.setFields(czlist.get(tblCourse.getSelectedRow()));
    }//GEN-LAST:event_btnDeleteCzActionPerformed

    private void btnDeleteInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteInsActionPerformed
        
        DeleteInstructor di = new DeleteInstructor();
        di.setVisible(true);
        di.setFields(inlist.get(tblInstruct.getSelectedRow()));
    }//GEN-LAST:event_btnDeleteInsActionPerformed

    private void btnViewInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewInsActionPerformed
        
        ViewInstructor vi = new ViewInstructor();
        vi.setVisible(true);
        vi.setFields(inlist.get(tblInstruct.getSelectedRow()));
    }//GEN-LAST:event_btnViewInsActionPerformed

    private void btnUpdateInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateInsActionPerformed
        
        UpdateInstructor ui = new UpdateInstructor();
        ui.setVisible(true);
        ui.setFields(inlist.get(tblInstruct.getSelectedRow()));
    }//GEN-LAST:event_btnUpdateInsActionPerformed

    private void btnSearch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch3ActionPerformed
        try{
            con = (Connection) DriverManager.getConnection(url, username, password);
            String name = txtSearchName2.getText();
            String sql = "Select instructId , instructName , email , telNo , depName from instructordetails where instructName LIKE '%"+name+"%' ";
            pst = (PreparedStatement) con.prepareStatement(sql); 
            res = pst.executeQuery();
            
            tblInstruct.setModel(DbUtils.resultSetToTableModel(res));
       }catch(Exception e){
               
               }
    }//GEN-LAST:event_btnSearch3ActionPerformed

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
         try{
            con = (Connection) DriverManager.getConnection(url, username, password);
            String name = txtSearchName.getText();
            String sql = "Select cozId , subName , credit ,  depName , semester , lecName , labNo , cozFee from coursedetails where subName LIKE '%"+name+"%' ";
            pst = (PreparedStatement) con.prepareStatement(sql); 
            res = pst.executeQuery();
            
            tblCourse.setModel(DbUtils.resultSetToTableModel(res));
       }catch(Exception e){
               
               }
    }//GEN-LAST:event_btnSearch2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Save.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Save.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Save.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Save.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Save().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCz;
    private javax.swing.JButton btnAddDep;
    private javax.swing.JButton btnAddIns;
    private javax.swing.JButton btnAddLec;
    private javax.swing.JButton btnDeleteCz;
    private javax.swing.JButton btnDeleteIns;
    private javax.swing.JButton btnDeleteLec;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JButton btnSearch3;
    private javax.swing.JButton btnUpdateCz;
    private javax.swing.JButton btnUpdateIns;
    private javax.swing.JButton btnUpdateLec;
    private javax.swing.JButton btnViewCz;
    private javax.swing.JButton btnViewIns;
    private javax.swing.JButton btnViewLec;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblCourse;
    private javax.swing.JTable tblDep;
    private javax.swing.JTable tblInstruct;
    private javax.swing.JTable txtLec;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearchName;
    private javax.swing.JTextField txtSearchName2;
    // End of variables declaration//GEN-END:variables
}
