/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbmuniversity;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Asangi
 */
public class StudentDetails extends javax.swing.JFrame {

    String url = "jdbc:mysql://localhost:3306/nsbmuniversity";
    String username = "root";
    String password = "";
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet res = null;
    PreparedStatement pst1 = null;
    ResultSet res1 = null;
    PreparedStatement pst2 = null;
    ResultSet res2 = null;
    PreparedStatement pst3 = null;
    ResultSet res3 = null;
    PreparedStatement pst4 = null;
    ResultSet res4 = null;

    /**
     * Creates new form StudentDetails
     */
    public StudentDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnEnter = new javax.swing.JButton();
        txtRegId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNameIni = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTelNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtSemOneSubOne = new javax.swing.JTextField();
        txtSemOneSubTwo = new javax.swing.JTextField();
        txtSemOneSubThree = new javax.swing.JTextField();
        txtSemOneSubFour = new javax.swing.JTextField();
        txtSemTwoSubOne = new javax.swing.JTextField();
        txtSemTwoSubTwo = new javax.swing.JTextField();
        txtSemTwoSubThree = new javax.swing.JTextField();
        txtSemTwoSubFour = new javax.swing.JTextField();
        txtDepName = new javax.swing.JTextField();
        txtYearOfReg = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Subject 3 for Sem 2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Details");
        getContentPane().setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("RegId");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 36, 108, 23);

        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnter);
        btnEnter.setBounds(234, 36, 82, 23);

        txtRegId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtRegId);
        txtRegId.setBounds(142, 37, 74, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Student Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 77, 108, 24);
        getContentPane().add(txtNameIni);
        txtNameIni.setBounds(142, 81, 204, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("National Id");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 127, 108, 25);
        getContentPane().add(txtNIC);
        txtNIC.setBounds(142, 131, 313, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Email Address");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(31, 170, 107, 24);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(142, 170, 313, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Telephone No");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(27, 205, 111, 24);

        txtTelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelNoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelNo);
        txtTelNo.setBounds(142, 209, 313, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Department Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(25, 240, 113, 23);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Year of Registration");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(19, 281, 119, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Subject 1 for Sem 1");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 317, 128, 26);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Subject 2 for Sem 1");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 349, 128, 26);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Subject 3 for Sem 1");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 381, 128, 26);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Subject 4 for Sem 1");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 413, 128, 26);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Subject 1 for Sem 2");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 445, 128, 26);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Subject 2 for Sem 2");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 477, 128, 26);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Subject 3 for Sem 2");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 509, 128, 26);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Subject 4 for Sem 2");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 538, 128, 26);
        getContentPane().add(txtSemOneSubOne);
        txtSemOneSubOne.setBounds(142, 322, 313, 20);
        getContentPane().add(txtSemOneSubTwo);
        txtSemOneSubTwo.setBounds(142, 354, 313, 20);

        txtSemOneSubThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSemOneSubThreeActionPerformed(evt);
            }
        });
        getContentPane().add(txtSemOneSubThree);
        txtSemOneSubThree.setBounds(142, 386, 313, 20);
        getContentPane().add(txtSemOneSubFour);
        txtSemOneSubFour.setBounds(142, 418, 313, 20);
        getContentPane().add(txtSemTwoSubOne);
        txtSemTwoSubOne.setBounds(142, 450, 313, 20);
        getContentPane().add(txtSemTwoSubTwo);
        txtSemTwoSubTwo.setBounds(142, 482, 313, 20);
        getContentPane().add(txtSemTwoSubThree);
        txtSemTwoSubThree.setBounds(142, 514, 313, 20);
        getContentPane().add(txtSemTwoSubFour);
        txtSemTwoSubFour.setBounds(142, 543, 313, 20);
        getContentPane().add(txtDepName);
        txtDepName.setBounds(142, 243, 313, 20);
        getContentPane().add(txtYearOfReg);
        txtYearOfReg.setBounds(142, 284, 89, 20);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(334, 36, 119, 23);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(471, 36, 116, 23);

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(142, 575, 123, 36);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 610, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        try {
            con = (Connection) DriverManager.getConnection(url, username, password);
            pst = con.prepareStatement("SELECT registerdetailspart1.name ,registerdetailspart1.NIC , registerdetailspart1.email ,registerdetailspart1.telNo FROM registerdetailspart1 WHERE registerdetailspart1.regId = '" + txtRegId.getText() + "' ");

            res = pst.executeQuery();

            while (res.next()) {
                String name = res.getString(1);
                String NIC = res.getString(2);
                String email = res.getString(3);
                String telNo = res.getString(4);
                txtNameIni.setText(name);
                txtNIC.setText(NIC);
                txtEmail.setText(email);
                txtTelNo.setText(telNo);
            }

            pst1 = con.prepareStatement("SELECT undergraduateenrolledcourse.regId FROM undergraduateenrolledcourse WHERE undergraduateenrolledcourse.regId = '" + txtRegId.getText() + "'");
            res1 = pst1.executeQuery();
            
            int regId1 = 0;
            int regId2 = 0;
            int regId3 = 0;
            int regId4 = 0;
            
            while (res1.next()) {
                regId1 = res1.getInt(1);
            }
            pst2 = con.prepareStatement("SELECT undergraduateenrolledcourse2.regId FROM undergraduateenrolledcourse2 WHERE undergraduateenrolledcourse2.regId = '" + txtRegId.getText() + "'");
            res2 = pst2.executeQuery();
            while (res2.next()) {
                regId2 = res2.getInt(1);
            }
            
            pst3 = con.prepareStatement("SELECT enrolledcourse.regId FROM enrolledcourse WHERE enrolledcourse.regId = '" + txtRegId.getText() + "'");
            res3 = pst3.executeQuery();
            while (res3.next()) {
                regId3 = res3.getInt(1);
            }
            
            pst4 = con.prepareStatement("SELECT enrolledcourse2.regId FROM enrolledcourse2 WHERE enrolledcourse2.regId = '" + txtRegId.getText() + "'");
            res4 = pst4.executeQuery();
            while (res4.next()) {
                regId4 = res4.getInt(1);
            }
            
            if (Integer.parseInt(txtRegId.getText()) == regId1) {
                pst1 = con.prepareStatement("SELECT undergraduateenrolledcourse.depName , undergraduateenrolledcourse.yearOfReg , undergraduateenrolledcourse.semOneSubOne , undergraduateenrolledcourse.semOneSubTwo ,undergraduateenrolledcourse.semOneSubThree , undergraduateenrolledcourse.semOneSubFour , undergraduateenrolledcourse.semTwoSubOne ,undergraduateenrolledcourse.semTwoSubTwo,undergraduateenrolledcourse.semTwoSubThree ,undergraduateenrolledcourse.semTwoSubFour FROM undergraduateenrolledcourse WHERE undergraduateenrolledcourse.regId = '" + txtRegId.getText() + "' ");
                res1 = pst1.executeQuery();

                while (res1.next()) {
                    String depName = res1.getString(1);
                    String yearOfReg = res1.getString(2);
                    String semOneSubOne = res1.getString(3);
                    String semOneSubTwo = res1.getString(4);
                    String semOneSubThree = res1.getString(5);
                    String semOneSubFour = res1.getString(6);
                    String semTwoSubOne = res1.getString(7);
                    String semTwoSubTwo = res1.getString(8);
                    String semTwoSubThree = res1.getString(9);
                    String semTwoSubFour = res1.getString(10);
                    txtDepName.setText(depName);
                    txtYearOfReg.setText(yearOfReg);
                    txtSemOneSubOne.setText(semOneSubOne);
                    txtSemOneSubTwo.setText(semOneSubTwo);
                    txtSemOneSubThree.setText(semOneSubThree);
                    txtSemOneSubFour.setText(semOneSubFour);
                    txtSemTwoSubOne.setText(semTwoSubOne);
                    txtSemTwoSubTwo.setText(semTwoSubTwo);
                    txtSemTwoSubThree.setText(semTwoSubThree);
                    txtSemTwoSubFour.setText(semTwoSubFour);
                }
            }else if (Integer.parseInt(txtRegId.getText()) == regId2) {
                pst2 = con.prepareStatement("SELECT undergraduateenrolledcourse2.depName , undergraduateenrolledcourse2.yearOfReg , undergraduateenrolledcourse2.semTwoSubOne ,undergraduateenrolledcourse2.semTwoSubTwo,undergraduateenrolledcourse2.semTwoSubThree ,undergraduateenrolledcourse2.semTwoSubFour FROM undergraduateenrolledcourse2 WHERE undergraduateenrolledcourse2.regId = '" + txtRegId.getText() + "' ");
                res2 = pst2.executeQuery();

                while (res2.next()) {
                    String depName = res2.getString(1);
                    String yearOfReg = res2.getString(2);

                    String semTwoSubOne = res2.getString(3);
                    String semTwoSubTwo = res2.getString(4);
                    String semTwoSubThree = res2.getString(5);
                    String semTwoSubFour = res2.getString(6);
                    txtDepName.setText(depName);
                    txtYearOfReg.setText(yearOfReg);

                    txtSemTwoSubOne.setText(semTwoSubOne);
                    txtSemTwoSubTwo.setText(semTwoSubTwo);
                    txtSemTwoSubThree.setText(semTwoSubThree);
                    txtSemTwoSubFour.setText(semTwoSubFour);
                }
            }else if (Integer.parseInt(txtRegId.getText()) == regId3) {
                pst3 = con.prepareStatement("SELECT enrolledcourse.depName , enrolledcourse.yearOfReg , enrolledcourse.semOneSubOne , enrolledcourse.semOneSubTwo ,enrolledcourse.semOneSubThree , enrolledcourse.semOneSubFour , enrolledcourse.semTwoSubOne ,enrolledcourse.semTwoSubTwo,enrolledcourse.semTwoSubThree ,enrolledcourse.semTwoSubFour FROM enrolledcourse WHERE enrolledcourse.regId = '" + txtRegId.getText() + "' ");
                res3 = pst3.executeQuery();

                while (res3.next()) {
                    String depName = res3.getString(1);
                    String yearOfReg = res3.getString(2);
                    String semOneSubOne = res3.getString(3);
                    String semOneSubTwo = res3.getString(4);
                    String semOneSubThree = res3.getString(5);
                    String semOneSubFour = res3.getString(6);
                    String semTwoSubOne = res3.getString(7);
                    String semTwoSubTwo = res3.getString(8);
                    String semTwoSubThree = res3.getString(9);
                    String semTwoSubFour = res3.getString(10);
                    txtDepName.setText(depName);
                    txtYearOfReg.setText(yearOfReg);
                    txtSemOneSubOne.setText(semOneSubOne);
                    txtSemOneSubTwo.setText(semOneSubTwo);
                    txtSemOneSubThree.setText(semOneSubThree);
                    txtSemOneSubFour.setText(semOneSubFour);
                    txtSemTwoSubOne.setText(semTwoSubOne);
                    txtSemTwoSubTwo.setText(semTwoSubTwo);
                    txtSemTwoSubThree.setText(semTwoSubThree);
                    txtSemTwoSubFour.setText(semTwoSubFour);
                }
            }else if (Integer.parseInt(txtRegId.getText()) == regId4) {
                pst4 = con.prepareStatement("SELECT enrolledcourse2.depName , enrolledcourse2.yearOfReg , enrolledcourse2.semTwoSubOne ,enrolledcourse2.semTwoSubTwo,enrolledcourse2.semTwoSubThree ,enrolledcourse2.semTwoSubFour FROM enrolledcourse2 WHERE enrolledcourse2.regId = '" + txtRegId.getText() + "' ");
                res4 = pst4.executeQuery();

                while (res4.next()) {
                    String depName = res4.getString(1);
                    String yearOfReg = res4.getString(2);

                    String semTwoSubOne = res4.getString(3);
                    String semTwoSubTwo = res4.getString(4);
                    String semTwoSubThree = res4.getString(5);
                    String semTwoSubFour = res4.getString(6);
                    txtDepName.setText(depName);
                    txtYearOfReg.setText(yearOfReg);

                    txtSemTwoSubOne.setText(semTwoSubOne);
                    txtSemTwoSubTwo.setText(semTwoSubTwo);
                    txtSemTwoSubThree.setText(semTwoSubThree);
                    txtSemTwoSubFour.setText(semTwoSubFour);
                }
            }

        } catch (Exception e) {
            System.out.println("x");
            System.out.println(e);
        }


    }//GEN-LAST:event_btnEnterActionPerformed

    private void txtRegIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegIdActionPerformed

    private void txtTelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelNoActionPerformed

    private void txtSemOneSubThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSemOneSubThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSemOneSubThreeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try{
            String query1 = "SELECT registerdetailspart2.regId FROM registerdetailspart2 WHERE registerdetailspart2.regId = '"+txtRegId.getText()+"'";
            String query2 = "SELECT postgraduatedetails.regId FROM postgraduatedetails WHERE postgraduatedetails.regId = '"+txtRegId.getText()+"'";
            String query3 = "SELECT undergraduateenrolledcourse.regId FROM undergraduateenrolledcourse WHERE undergraduateenrolledcourse.regId = '"+txtRegId.getText()+"'";
            String query4 = "SELECT undergraduateenrolledcourse2.regId FROM undergraduateenrolledcourse2 WHERE undergraduateenrolledcourse2.regId = '"+txtRegId.getText()+"'";
            String query5 = "SELECT enrolledcourse.regId FROM enrolledcourse WHERE enrolledcourse.regId = '"+txtRegId.getText()+"'";
            String query6 = "SELECT enrolledcourse2.regId FROM enrolledcourse2 WHERE enrolledcourse2.regId = '"+txtRegId.getText()+"'";
            String x = txtRegId.getText();
            con = (Connection) DriverManager.getConnection(url, username, password);
            pst = con.prepareStatement("DELETE FROM registerdetailspart1 WHERE regId = "+txtRegId.getText());
            
            if(x == query1 && x == query3){
                pst = con.prepareStatement("DELETE FROM registerdetailspart2 WHERE regId = "+txtRegId.getText());
                pst = con.prepareStatement("DELETE FROM undergraduateenrolledcourse WHERE regId = "+txtRegId.getText());
                pst.executeUpdate();
            }
            
            else if(x == query1 && x == query4){
                pst = con.prepareStatement("DELETE FROM registerdetailspart2 WHERE regId = "+txtRegId.getText());
                pst = con.prepareStatement("DELETE FROM undergraduateenrolledcourse2 WHERE regId = "+txtRegId.getText());
                pst.executeUpdate();
            }
            
            else if(x == query2 && x == query5){
                pst = con.prepareStatement("DELETE FROM postgraduatedetails WHERE regId = "+txtRegId.getText());
                pst = con.prepareStatement("DELETE FROM enrolledcourse WHERE regId = "+txtRegId.getText());
                pst.executeUpdate();
            }
            
            else if(x == query2 && x == query6){
                pst = con.prepareStatement("DELETE FROM postgraduatedetails WHERE regId = "+txtRegId.getText());
                pst = con.prepareStatement("DELETE FROM enrolledcourse2 WHERE regId = "+txtRegId.getText());
                pst.executeUpdate();
            }
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Sucsess Delete");
        }catch(Exception e){
            System.out.println(""+e);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        this.dispose();
        StudentUpdate su = new StudentUpdate();
        su.setVisible(true);
        su.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtRegId.setText("");
        txtNameIni.setText("");
        txtNIC.setText("");
        txtEmail.setText("");
        txtTelNo.setText("");
        txtDepName.setText("");
        txtYearOfReg.setText("");
        txtSemOneSubOne.setText("");
        txtSemOneSubTwo.setText("");
        txtSemOneSubThree.setText("");
        txtSemOneSubFour.setText("");
        txtSemTwoSubOne.setText("");
        txtSemTwoSubTwo.setText("");
        txtSemTwoSubThree.setText("");
        txtSemTwoSubFour.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDepName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtNameIni;
    private javax.swing.JTextField txtRegId;
    private javax.swing.JTextField txtSemOneSubFour;
    private javax.swing.JTextField txtSemOneSubOne;
    private javax.swing.JTextField txtSemOneSubThree;
    private javax.swing.JTextField txtSemOneSubTwo;
    private javax.swing.JTextField txtSemTwoSubFour;
    private javax.swing.JTextField txtSemTwoSubOne;
    private javax.swing.JTextField txtSemTwoSubThree;
    private javax.swing.JTextField txtSemTwoSubTwo;
    private javax.swing.JTextField txtTelNo;
    private javax.swing.JTextField txtYearOfReg;
    // End of variables declaration//GEN-END:variables

}
