/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsbmuniversity;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Asangi
 */
public class UndergraduateEnrolledCourse1 extends javax.swing.JFrame {
    DBOperation dbops = new DBOperation();
    String url = "jdbc:mysql://localhost:3306/nsbmuniversity";
    String username = "root";
    String password = "";
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet res = null;
    /**
     * Creates new form UndergraduateEnrolledCourse
     */
    public UndergraduateEnrolledCourse1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNameIni = new javax.swing.JTextField();
        ddDepName = new javax.swing.JComboBox<>();
        ddYearOfReg = new javax.swing.JComboBox<>();
        ddSubTwoSemTwo = new javax.swing.JComboBox<>();
        ddCourse6Fee = new javax.swing.JComboBox<>();
        ddCourse7Fee = new javax.swing.JComboBox<>();
        ddCourse8Fee = new javax.swing.JComboBox<>();
        ddCourse5Fee = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        ddSubOneSemTwo = new javax.swing.JComboBox<>();
        ddSubThreeSemTwo = new javax.swing.JComboBox<>();
        ddSubFourSemTwo = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        txtRegId = new javax.swing.JTextField();
        txtfive = new javax.swing.JTextField();
        txtfeefive = new javax.swing.JTextField();
        txtsix = new javax.swing.JTextField();
        txtfeesix = new javax.swing.JTextField();
        txtseven = new javax.swing.JTextField();
        txtfeeseven = new javax.swing.JTextField();
        txteight = new javax.swing.JTextField();
        txtfeeeight = new javax.swing.JTextField();
        txttotal1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtNameIni1 = new javax.swing.JTextField();
        ddDepName1 = new javax.swing.JComboBox<>();
        ddYearOfReg1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        ddSubTwoSemOne4 = new javax.swing.JComboBox<>();
        ddSubOneSemOne4 = new javax.swing.JComboBox<>();
        ddSubFourSemOne4 = new javax.swing.JComboBox<>();
        ddSubThreeSemOne4 = new javax.swing.JComboBox<>();
        ddCourse5Fee1 = new javax.swing.JComboBox<>();
        ddCourse6Fee1 = new javax.swing.JComboBox<>();
        ddCourse7Fee1 = new javax.swing.JComboBox<>();
        ddCourse8Fee1 = new javax.swing.JComboBox<>();
        btnSave1 = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        txtRegId1 = new javax.swing.JTextField();
        txtfive1 = new javax.swing.JTextField();
        txtfeefive1 = new javax.swing.JTextField();
        txtsix1 = new javax.swing.JTextField();
        txtfeesix1 = new javax.swing.JTextField();
        txtseven1 = new javax.swing.JTextField();
        txtfeeseven1 = new javax.swing.JTextField();
        txteight1 = new javax.swing.JTextField();
        txtfeeeight1 = new javax.swing.JTextField();
        txttotal2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enrolled for Undegraduate Student");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Student Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Department Name");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Year of Registration");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Subject 1 for Sem 2");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Subject 2 for Sem 2");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Subject 3 for Sem 2");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Subject 4 for Sem 2");

        ddDepName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School of Business", "School of Computing", "School of Engineering" }));

        ddYearOfReg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019" }));
        ddYearOfReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddYearOfRegActionPerformed(evt);
            }
        });

        ddSubTwoSemTwo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Data Structure and Algo", "Statics", "Mathematical Method" }));
        ddSubTwoSemTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddSubTwoSemTwoActionPerformed(evt);
            }
        });

        ddCourse6Fee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2500", "3000", "3500", "4000" }));
        ddCourse6Fee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddCourse6FeeActionPerformed(evt);
            }
        });

        ddCourse7Fee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2500", "3000", "3500", "4000" }));

        ddCourse8Fee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2500", "3000", "3500", "4000" }));

        ddCourse5Fee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2500", "3000", "3500", "4000" }));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        ddSubOneSemTwo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Programming", "Discrete Mathematics", "Laboratary" }));
        ddSubOneSemTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddSubOneSemTwoActionPerformed(evt);
            }
        });

        ddSubThreeSemTwo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Database", "Computer Network", "Automata" }));
        ddSubThreeSemTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddSubThreeSemTwoActionPerformed(evt);
            }
        });

        ddSubFourSemTwo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software Engineering", "Foundation of Computer Seince", "Computer System" }));
        ddSubFourSemTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddSubFourSemTwoActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Select Subject Completing 9 Credit for 3rd Year Student");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("Reg Id");

        txtRegId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegIdActionPerformed(evt);
            }
        });

        txtfeesix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfeesixActionPerformed(evt);
            }
        });

        jButton2.setText("Total");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNameIni, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(ddDepName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(73, 73, 73)))
                            .addComponent(txtRegId, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ddYearOfReg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ddSubThreeSemTwo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ddSubTwoSemTwo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ddSubFourSemTwo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ddSubOneSemTwo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txttotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtfive, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtfeefive, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtsix, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtseven, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(20, 20, 20)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtfeeseven, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtfeesix)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txteight, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(23, 23, 23)
                                                .addComponent(txtfeeeight)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(ddCourse8Fee, 0, 91, Short.MAX_VALUE)
                                                .addComponent(ddCourse6Fee, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ddCourse7Fee, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(ddCourse5Fee, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(268, 268, 268))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddDepName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddYearOfReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddSubOneSemTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddCourse5Fee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfeefive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddSubTwoSemTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddCourse6Fee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfeesix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddCourse7Fee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddSubFourSemTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ddCourse8Fee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txteight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfeeeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ddSubThreeSemTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtseven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtfeeseven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("3rd Years", jPanel2);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Student Name");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Department Name");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Year of Registration");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Subject 1 for Sem 2");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Subject 2 for Sem 2");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Subject 3 for Sem 2");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Subject 4 for Sem 2");

        ddDepName1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School of Business", "School of Computing", "School of Engineering" }));

        ddYearOfReg1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018", "2019" }));
        ddYearOfReg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddYearOfReg1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Select Subject Completing 11 Credit for 4th year Student");

        ddSubTwoSemOne4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Programming", "Discrete Mathematics", "Laboratary" }));
        ddSubTwoSemOne4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddSubTwoSemOne4ActionPerformed(evt);
            }
        });

        ddSubOneSemOne4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Data Structure and Algo", "Statics", "Mathematical Method" }));
        ddSubOneSemOne4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddSubOneSemOne4ActionPerformed(evt);
            }
        });

        ddSubFourSemOne4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Database", "Computer Network", "Automata" }));
        ddSubFourSemOne4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddSubFourSemOne4ActionPerformed(evt);
            }
        });

        ddSubThreeSemOne4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software Engineering", "Foundation of Computer Seince", "Computer System" }));
        ddSubThreeSemOne4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddSubThreeSemOne4ActionPerformed(evt);
            }
        });

        ddCourse5Fee1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2500", "3000", "3500", "4000" }));
        ddCourse5Fee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddCourse5Fee1ActionPerformed(evt);
            }
        });

        ddCourse6Fee1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2500", "3000", "3500", "4000" }));
        ddCourse6Fee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddCourse6Fee1ActionPerformed(evt);
            }
        });

        ddCourse7Fee1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2500", "3000", "3500", "4000" }));

        ddCourse8Fee1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2500", "3000", "3500", "4000" }));

        btnSave1.setText("Save");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });

        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("Reg Id");

        txtRegId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegId1ActionPerformed(evt);
            }
        });

        txtfeesix1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfeesix1ActionPerformed(evt);
            }
        });

        jButton3.setText("Total");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNameIni1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ddDepName1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ddYearOfReg1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(ddSubOneSemOne4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtsix1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(ddSubTwoSemOne4, javax.swing.GroupLayout.Alignment.LEADING, 0, 187, Short.MAX_VALUE)
                                                    .addComponent(ddSubFourSemOne4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(ddSubThreeSemOne4, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtfive1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtseven1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txteight1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txttotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtfeefive1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                            .addComponent(txtfeesix1)
                                            .addComponent(txtfeeseven1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtfeeeight1))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ddCourse5Fee1, javax.swing.GroupLayout.Alignment.LEADING, 0, 96, Short.MAX_VALUE)
                                    .addComponent(ddCourse6Fee1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ddCourse7Fee1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ddCourse8Fee1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtRegId1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameIni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddDepName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddYearOfReg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddSubTwoSemOne4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddCourse5Fee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfive1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfeefive1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddSubOneSemOne4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddCourse6Fee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsix1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfeesix1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ddSubFourSemOne4)
                        .addComponent(txtseven1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtfeeseven1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ddCourse7Fee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddSubThreeSemOne4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddCourse8Fee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txteight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfeeeight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("4th Years", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ddYearOfRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddYearOfRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddYearOfRegActionPerformed

    private void ddSubTwoSemTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddSubTwoSemTwoActionPerformed
        try {
                con = (Connection) DriverManager.getConnection(url, username, password);
                pst = con.prepareStatement("SELECT coursedetails.credit , coursedetails.cozFee FROM coursedetails WHERE coursedetails.subName = '" + ddSubTwoSemTwo.getSelectedItem().toString() + "' ");

                res = pst.executeQuery();
                while (res.next()) {
                    int credit = res.getInt(1);
                    String fee  = res.getString(2);
                    txtsix.setText(Integer.toString(credit));
                    txtfeesix.setText(fee);
                
            }
            }catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_ddSubTwoSemTwoActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(Integer.parseInt(txttotal1.getText())==9) {
        this.dispose();
        UndergraduateEnrolledCourse2Details ecd2 = new UndergraduateEnrolledCourse2Details();
        ecd2.setRegId(Integer.parseInt(txtRegId.getText()));
        ecd2.setName(txtNameIni.getText());
        ecd2.setDepName(ddDepName.getSelectedItem().toString());
        ecd2.setYearOfReg(ddYearOfReg.getSelectedItem().toString());
        ecd2.setSemTwoSubOne(ddSubOneSemTwo.getSelectedItem().toString());
        ecd2.setCourseFiveFee(Integer.parseInt(ddCourse5Fee.getSelectedItem().toString()));
        ecd2.setSemTwoSubTwo(ddSubTwoSemTwo.getSelectedItem().toString());
        ecd2.setCourseSixFee(Integer.parseInt(ddCourse6Fee.getSelectedItem().toString()));
        ecd2.setSemTwoSubThree(ddSubThreeSemTwo.getSelectedItem().toString());
        ecd2.setCourseSevenFee(Integer.parseInt(ddCourse7Fee.getSelectedItem().toString()));
        ecd2.setSemTwoSubFour(ddSubFourSemTwo.getSelectedItem().toString());
        ecd2.setCourseEghitFee(Integer.parseInt(ddCourse8Fee.getSelectedItem().toString()));
        if(dbops.UndergraduateEnrolledCourse2(ecd2)){
            JOptionPane.showMessageDialog(this, "Succsefully !!");
            clearField();
        }
        else{
            JOptionPane.showMessageDialog(this, "Unsuccessfully!!");
            clearField();
        }
        }else {
            JOptionPane.showMessageDialog(this, "Please complete amount of credit  correctly");
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    void clearField(){
          txtNameIni.setText("");
    }
    private void ddYearOfReg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddYearOfReg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddYearOfReg1ActionPerformed

    private void ddSubOneSemOne4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddSubOneSemOne4ActionPerformed
        try {
                con = (Connection) DriverManager.getConnection(url, username, password);
                pst = con.prepareStatement("SELECT coursedetails.credit , coursedetails.cozFee FROM coursedetails WHERE coursedetails.subName = '" + ddSubOneSemOne4.getSelectedItem().toString() + "' ");

                res = pst.executeQuery();
                while (res.next()) {
                    int credit = res.getInt(1);
                    String fee  = res.getString(2);
                    txtsix1.setText(Integer.toString(credit));
                    txtfeesix1.setText(fee);
                
            }
            }catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_ddSubOneSemOne4ActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        if(Integer.parseInt(txttotal1.getText())==11 ){
        this.dispose();
        EnrolledCourseDetails2 ecd2 = new EnrolledCourseDetails2();
        ecd2.setRegId(Integer.parseInt(txtRegId.getText()));
        ecd2.setName(txtNameIni.getText());
        ecd2.setDepName(ddDepName.getSelectedItem().toString());
        ecd2.setYearOfReg(ddYearOfReg.getSelectedItem().toString());
        ecd2.setSemTwoSubOne(ddSubOneSemTwo.getSelectedItem().toString());
        ecd2.setCourseFiveFee(Integer.parseInt(ddCourse5Fee.getSelectedItem().toString()));
        ecd2.setSemTwoSubOne(ddSubTwoSemTwo.getSelectedItem().toString());
        ecd2.setCourseSixFee(Integer.parseInt(ddCourse6Fee.getSelectedItem().toString()));
        ecd2.setSemTwoSubThree(ddSubThreeSemTwo.getSelectedItem().toString());
        ecd2.setCourseSevenFee(Integer.parseInt(ddCourse7Fee.getSelectedItem().toString()));
        ecd2.setSemTwoSubFour(ddSubFourSemTwo.getSelectedItem().toString());
        ecd2.setCourseEghitFee(Integer.parseInt(ddCourse8Fee.getSelectedItem().toString()));
        if(dbops.EnrolledCourse2(ecd2)){
            JOptionPane.showMessageDialog(this, "Succsefully !!");
            clearField();
        }
        else{
            JOptionPane.showMessageDialog(this, "Unsuccessfully!!");
            clearField();
        }
        }else {
            JOptionPane.showMessageDialog(this, "Please complete amount of credit  correctly");
        }
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.hide();
        RegisterPart2 rp2 = new  RegisterPart2();
        rp2.setVisible(true);
        rp2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        this.hide();
        RegisterPart2 rp2 = new  RegisterPart2();
        rp2.setVisible(true);
        rp2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void ddSubThreeSemTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddSubThreeSemTwoActionPerformed
        try {
                con = (Connection) DriverManager.getConnection(url, username, password);
                pst = con.prepareStatement("SELECT coursedetails.credit , coursedetails.cozFee FROM coursedetails WHERE coursedetails.subName = '" + ddSubThreeSemTwo.getSelectedItem().toString() + "' ");

                res = pst.executeQuery();
                while (res.next()) {
                    int credit = res.getInt(1);
                    String fee = res.getString(2);
                    txtseven.setText(Integer.toString(credit));
                    txtfeeseven.setText(fee);
            }
            }catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_ddSubThreeSemTwoActionPerformed

    private void ddCourse6FeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddCourse6FeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddCourse6FeeActionPerformed

    private void ddCourse5Fee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddCourse5Fee1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddCourse5Fee1ActionPerformed

    private void ddCourse6Fee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddCourse6Fee1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddCourse6Fee1ActionPerformed

    private void txtRegIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegIdActionPerformed

    private void txtRegId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegId1ActionPerformed

    private void txtfeesixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfeesixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfeesixActionPerformed

    private void txtfeesix1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfeesix1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfeesix1ActionPerformed

    private void ddSubOneSemTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddSubOneSemTwoActionPerformed
       try {
                con = (Connection) DriverManager.getConnection(url, username, password);
                pst = con.prepareStatement("SELECT coursedetails.credit , coursedetails.cozFee FROM coursedetails WHERE coursedetails.subName = '" + ddSubOneSemTwo.getSelectedItem().toString() + "' ");

                res = pst.executeQuery();
                while (res.next()) {
                    int credit = res.getInt(1);
                    String fee = res.getString(2);
                    txtfive.setText(Integer.toString(credit));
                    txtfeefive.setText(fee);
            }
            }catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_ddSubOneSemTwoActionPerformed

    private void ddSubFourSemTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddSubFourSemTwoActionPerformed
        try {
                con = (Connection) DriverManager.getConnection(url, username, password);
                pst = con.prepareStatement("SELECT coursedetails.credit ,coursedetails.cozFee  FROM coursedetails WHERE coursedetails.subName = '" + ddSubFourSemTwo.getSelectedItem().toString() + "' ");

                res = pst.executeQuery();
                while (res.next()) {
                    int credit = res.getInt(1);
                    String fee = res.getString(2);
                    txteight.setText(Integer.toString(credit));
                    txtfeeeight.setText(fee);
                
            }
            }catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_ddSubFourSemTwoActionPerformed

    private void ddSubTwoSemOne4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddSubTwoSemOne4ActionPerformed
        try {
                con = (Connection) DriverManager.getConnection(url, username, password);
                pst = con.prepareStatement("SELECT coursedetails.credit , coursedetails.cozFee FROM coursedetails WHERE coursedetails.subName = '" + ddSubTwoSemOne4.getSelectedItem().toString() + "' ");

                res = pst.executeQuery();
                while (res.next()) {
                    int credit = res.getInt(1);
                    String fee = res.getString(2);
                    txtfive1.setText(Integer.toString(credit));
                    txtfeefive1.setText(fee);
            }
            }catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_ddSubTwoSemOne4ActionPerformed

    private void ddSubFourSemOne4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddSubFourSemOne4ActionPerformed
        try {
                con = (Connection) DriverManager.getConnection(url, username, password);
                pst = con.prepareStatement("SELECT coursedetails.credit , coursedetails.cozFee FROM coursedetails WHERE coursedetails.subName = '" + ddSubFourSemOne4.getSelectedItem().toString() + "' ");

                res = pst.executeQuery();
                while (res.next()) {
                    int credit = res.getInt(1);
                    String fee = res.getString(2);
                    txtseven1.setText(Integer.toString(credit));
                    txtfeeseven1.setText(fee);
            }
            }catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_ddSubFourSemOne4ActionPerformed

    private void ddSubThreeSemOne4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddSubThreeSemOne4ActionPerformed
       try {
                con = (Connection) DriverManager.getConnection(url, username, password);
                pst = con.prepareStatement("SELECT coursedetails.credit ,coursedetails.cozFee  FROM coursedetails WHERE coursedetails.subName = '" + ddSubThreeSemOne4.getSelectedItem().toString() + "' ");

                res = pst.executeQuery();
                while (res.next()) {
                    int credit = res.getInt(1);
                    String fee = res.getString(2);
                    txteight1.setText(Integer.toString(credit));
                    txtfeeeight1.setText(fee);
                
            }
            }catch(Exception e){
                System.out.println(e);
            }
    }//GEN-LAST:event_ddSubThreeSemOne4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        int cre5 = Integer.parseInt(txtfive.getText());
        int cre6 = Integer.parseInt(txtsix.getText());
        int cre7 = Integer.parseInt(txtseven.getText());
        int cre8 = Integer.parseInt(txteight.getText());
        int total = cre5+cre6+cre7+cre8;
        txttotal1.setText(Integer.toString(total));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int cre5 = Integer.parseInt(txtfive1.getText());
        int cre6 = Integer.parseInt(txtsix1.getText());
        int cre7 = Integer.parseInt(txtseven1.getText());
        int cre8 = Integer.parseInt(txteight1.getText());
        int total = cre5+cre6+cre7+cre8;
        txttotal2.setText(Integer.toString(total));
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UndergraduateEnrolledCourse1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UndergraduateEnrolledCourse1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UndergraduateEnrolledCourse1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UndergraduateEnrolledCourse1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UndergraduateEnrolledCourse1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave1;
    private javax.swing.JComboBox<String> ddCourse5Fee;
    private javax.swing.JComboBox<String> ddCourse5Fee1;
    private javax.swing.JComboBox<String> ddCourse6Fee;
    private javax.swing.JComboBox<String> ddCourse6Fee1;
    private javax.swing.JComboBox<String> ddCourse7Fee;
    private javax.swing.JComboBox<String> ddCourse7Fee1;
    private javax.swing.JComboBox<String> ddCourse8Fee;
    private javax.swing.JComboBox<String> ddCourse8Fee1;
    private javax.swing.JComboBox<String> ddDepName;
    private javax.swing.JComboBox<String> ddDepName1;
    private javax.swing.JComboBox<String> ddSubFourSemOne4;
    private javax.swing.JComboBox<String> ddSubFourSemTwo;
    private javax.swing.JComboBox<String> ddSubOneSemOne4;
    private javax.swing.JComboBox<String> ddSubOneSemTwo;
    private javax.swing.JComboBox<String> ddSubThreeSemOne4;
    private javax.swing.JComboBox<String> ddSubThreeSemTwo;
    private javax.swing.JComboBox<String> ddSubTwoSemOne4;
    private javax.swing.JComboBox<String> ddSubTwoSemTwo;
    private javax.swing.JComboBox<String> ddYearOfReg;
    private javax.swing.JComboBox<String> ddYearOfReg1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtNameIni;
    private javax.swing.JTextField txtNameIni1;
    private javax.swing.JTextField txtRegId;
    private javax.swing.JTextField txtRegId1;
    private javax.swing.JTextField txteight;
    private javax.swing.JTextField txteight1;
    private javax.swing.JTextField txtfeeeight;
    private javax.swing.JTextField txtfeeeight1;
    private javax.swing.JTextField txtfeefive;
    private javax.swing.JTextField txtfeefive1;
    private javax.swing.JTextField txtfeeseven;
    private javax.swing.JTextField txtfeeseven1;
    private javax.swing.JTextField txtfeesix;
    private javax.swing.JTextField txtfeesix1;
    private javax.swing.JTextField txtfive;
    private javax.swing.JTextField txtfive1;
    private javax.swing.JTextField txtseven;
    private javax.swing.JTextField txtseven1;
    private javax.swing.JTextField txtsix;
    private javax.swing.JTextField txtsix1;
    private javax.swing.JTextField txttotal1;
    private javax.swing.JTextField txttotal2;
    // End of variables declaration//GEN-END:variables
}
